language: ruby
jdk:
- oraclejdk8
sudo: false
rvm:
- 2.3.1
addons:
  apt:
    packages:
before_install:
- openssl aes-256-cbc -K $encrypted_3beda31472b3_key -iv $encrypted_3beda31472b3_iv
  -in etc/secrets -out ../secrets.tar -d
- (cd ../ && tar xvf secrets.tar)
- chmod 600 ../release.asc
- gpg --import ../release.asc
install:
- rvm use 2.3.1
- gem install bundler
- bundle install
script: buildr clean package jacoco:report mcrt:publish_if_tagged
after_success:
- bash <(curl -s https://codecov.io/bash)
git:
  depth: false
env:
  global:
  - secure: lVFVwJa5PT8XC0HO27H/Z5c9eotNrqmHaoR9yQCN+urfWUSF18Pe8VkMi9BoXMWMECBQKhypF0lROAs2+XfbCclSrskTu//K1O5M7PHgjcsF+rRZcvzyk0JHLTecckZYHCCU4L9BExU4ggFXzQg+y8gQ7CMdF3sdI3yGqZ0N48Rnafeg2ojSLgOLhz3zNAS2IIgBMU9wjoaN7ZTaG9wN0jPHQM0w9aIlkNjx6OiK2UIeiRoOYlN55FvF6Zb2QO2JrHbVd3x+wiTNdThWIhLF/RLX4hQ9nq0A0g+lPtzn8syv6O0HQsnnPjuNYAXfR5Bh60ejp2pwyewEh9GqskxnDaZfPt6HFW4HFFLI+0RDjqaLkZ6ufAnvfMK/ZwqYecN6fVaxsScvGUSDRlqsA4NxfUSkbYXC1pUM8SuYjXQUwzvdsgzIgfyRqhr/v5yjvokH2P+/APcJdIH2iX6hlN5iuB4azxUWooHTDMMGLEd24ivwQZiYDYoRJ8OgXuF836Is2Uom0fIfxW5lr7VZUgbexOdixubwmpx46/f5+2xnhN/yI7xL0pUmbyoTEl0zBsf/vTNIJaehWG6f3VwjnRE4F9cGez5F8fhXlo7YJCHl2qnC8ByzS0eQtd7sOnJED+PdvFH+b47TSIAYf6NFoNTMC1cQqXcFjwn+wJWhB78wIyQ=
  - secure: sEdFeSddXOPzhIbevGvF/79OoUpAYGYeY0aK26pm4dXlxIY35IM53hN4ReP3pnFHyWYIFMBy6uNnuZYaMyVXwXGkKyFk7nS6IjbvMBca1dk0j5Z1WCW4R0wK8ahaLhZtkB8UV8KvxNRWSN0TNaz5o80+pYFT50z20VVVKtsVO9oCgaHKJ2s8aL6eSyN387Co3UXsbjHYrlrEYw9fl0AXqP2MTH4zpJlm5/uedTICjFmDVywGxLs6tk7JgWti0Xo+Qub63WStDK1D9Pm63qh+3EA7k8LyNBmJZquY+g/c6VdYpBdl4sBf9O5Okdp0ogfd08AI2mtaGSS93LQ9JoyWLT08WKNzBa1kWjZhns6dq0Vm7RNTuhwYLpamn2mG/56dDHCPZ+POKhJP2Lo7Oc42994GcMoV6/Bq5MvLehIc2h1hogN+Vbxu68kMKpLWw37rvqVY2H2rh1cyoKM3e5j548qSVucP8/K7xtYcqYZKz2oBMZaX1pPRKn0AfBDaxuiRbaplHVnERfcAIMNZzz9/6siOuSTiqRrlOvVP5nfA+P/AMhgxdB9HaTx7w7Llo5Mzn7l5SziiS5A9/8msnir+dH6gwDhyjsQzVbJFQkY+wUJkde5IBiMZOhJx5J8p8wZiSDqHFDJldj1VnWG5y5ZVl6RCYZX5wLQqDaElx4N1VU0=
  - secure: dcNAjCWHpXtMforPUKhBeUHzzRU+GPg8uck9YLzEdxGGF/g9qgvaTkmknwTvFZz3EDR/RcseX5OqY23wMURlcvdiMy+ZS5imyDBeMgFC/OaAL9SmZ16xan6QMwoF5cp67pfKT7mqLMg5Hpckv1tC19heEJ0CBW8EbRziM9ZaMDwlfCIpCJelpD8ydtzT31WOoH7OmpW42/fX2w8porHyIz4wqrxUdc1tj456U22TzonMSGHcj1VHzSn7TESTkyUOgpsjwPjHb8SSaDGUpLE+V1F3Z+gtiiIvYyYuOIZ61IbLFXQKetCLjaCGCbTt4UL5wqWYgX0qLifTvvVjrGP7j6mYD1+xZKG5enewg9R892Ptd89IHegN9FcxVgibpLeevkL4S1g5fOC0xt5UufMP95DDZommAEWdlNz6/b/X0tkKWNxdFFYShyQFRqAyYf5gliVjEfYyvHAeR9lgXv1itY92q023l9BHjoMeWaUwOjg0Z511BwKmxi4C4zdeGsj8tf15OdxIEMac3gw8Wrwy7TXlB0b/NtMIDFcZO0gPNaiWMQu+kQlHx0baN4ScGZ0PGufcWvA4k4OTdhIOefnEvt4BOVwgUWUBKdx2omF5nBQdvJFW/0M/NCgkHOWv2UR8bItuDHRqAXy2kWUlT93JJeMqIWsf4722Kj57bCEL4kE=
