language: ruby
jdk:
  - oraclejdk8
sudo: false
rvm:
  - 2.3.1
addons:
  apt:
    packages:
install:
  - rvm use 2.3.1
  - gem install bundler
  - bundle install
script: buildr clean package jacoco:report publish_if_tagged
after_success:
  - bash <(curl -s https://codecov.io/bash)
git:
  depth: 10
