language: ruby
jdk:
- oraclejdk8
sudo: false
rvm:
- 2.3.1
before_install:
- openssl aes-256-cbc -K $encrypted_3beda31472b3_key -iv $encrypted_3beda31472b3_iv
  -in etc/secrets -out ../secrets.tar -d
- "(cd ../ && tar xvf secrets.tar)"
- chmod 600 ../release.asc
- gpg --import ../release.asc
install:
- rvm use 2.3.1
- gem install bundler
- bundle install
script: buildr clean package jacoco:report mcrt:publish_if_tagged
after_success:
- bash <(curl -s https://codecov.io/bash)
git:
  depth: false
env:
  global:
  - secure: opJX0TVO+Yq8fKzxxo5ur6G1f7W5ttMZHtm9siLnKffPYx4ii2lIoZ0hT0k4IGCmyCBHtOb8rBOHZpznvM8Zukt7VoStPmdPUcNjJXPZiJ6wCdepfs8nRRl5EddoYGwZwkH6X+VmdoivKOjyD+1tjiyzmlzLalfA5tiYMdeCTZD6cP94oBH/uWYWsCEqEyBHbbe/Crd3UOOVJr24E5lefC2AnoGS+u21hZFML0tlGiFRpqYs054hLXW98OuZtY4YhrIEQLDJIjAH8kX720ha0hh1sHlbS/Zo5imoJfZcClsI4TFuxPlANOnPi2Nx9GBH6gyX85NlsBll77O1xgC62hAfN8vf9BI8H1Or9Y56fPeIcs23XOhfCNKyiHG4zVFwncnI/j+6BTZqQFdnfU5mhx72vk8NRW60hSA80LR2py3TNQaJi56HVflvs+MH6mLEOBcXgalLA0OffLwz0KhY0+1D3UqinC5B/fgJwKQN7EbrzpRQVStqxsQkVetWLx9SvZiKg3+T5cl9OvJLcd3UtmPsleJYtWwATZOhj2CZV8PKlD8TubDuuDwjwUSelLrcUFP/5uR8YNo2AnIvdlk51gRDtN7EyDybCOP0nz7SQVevjw53kv182mIsVPuJjADvdRi99QVlDFtWpQuInNaktbjxaaLolIPGt0GW1tAYc5Q=
  - secure: WFSzYLFM7+cEHRocW05mDeD6THwW/Gw8BqK49hMiNiPzS/0Pu9og0+l36lDUsFeHY7xpRrW/mQo9LV9fqsICMIUHAzjOs8z69DdOOF46QjG8izcxTUIR6gCOGBJq7KKht00BtUAsUOxITWACT6N0ni31K59QxWvFBKHJ/w4OyXNKHUN9lmSVot7/uQmh6MP7Ac4zZW8j14zgxE0gNqZV1X71IaR2V6grKOQMPX9FNmFbcZvrmUjJymWTdhRxzyhf9LotNj79KfQjzOJdjIsyhViAo7RVIuKhdCW874yeCHv59rnG6c1hJrLMUkVpT/1jQhKdsNt9CIS32xBUs+x67AB4K2kBufdjwzInPtbsECcwVA6JxfImJiEu9rm/ux6QavtzoI+vfgXn4mVi2Txvirn6Gze6OJFsQvBaAr86aqVRxz7zKopQKJKZqmEZPvxTMns9yOg4i0wZk2zGDyOFLQtFmOIIjKt+qnvINc+accJj3InWkMdRiuVj83cKNSsa/jq/ySLMmeIAyeJw8cx9Xuj7WKZOugP6rHu6YPehnfD5/YoljobV35+XzmSof/ETV/OiurzsKBHq5h4ZXAsa24ukjDjkvTKdQ4Cpyw/B4CVxvNfYB5AMGSKpvXJex4Fkpg/PbBeckFBfYQiscORjYDoBEcRT6mLRoNirwUvDjkE=
  - secure: XCbbDv8dAfigdXERltd6duqHoq1ybMXTBRLBlQjt0zJ4EbVGeDlcA+XOcq2EgWLT9ohpvkuRheqiDD5qmIfN4oxvnYTonSBQDR97SWjGEAB+Oi4l4ueB+N4DFLPvxzFO+v4UOxJUGeDvNwyKhJY1EPRnhp5xPVqV+G2KFdSA9o2LLanftMdnaxQQ9KvHwBosu2h745HWAvLX3pTaMYdBstetuDfgcRr8DCgBmCNE966YI0mwaUWLzo3szXnwTPdAAm0LslGV4xKNSqX1dOrn+wD629dhdIOZfshjkL6UdE1dnNal0LzbmwWJICfansR7D4wpY/G57ygSbwYDGnB0Lin866CPeRKCWiUw/IiI7nRc/hegVXlqWd9c+KY+S615GRn7iwJ12EFzWt/UfIYeo5JGenAHCx4cyDnzayIfxbCP5XvfghxHAqlhGKigIf+SkdgC2zErXm4eJaS1ZHBls56NlUIpcEzoH7ofFtM8GRxq8jksd6P/Sn33WRLnx6jaOk3/ojB2AgZS5an8V7NfaIRXPhzstiX/FTBX1h5h2rZcMXwiFuXH2jhe/xEZ6EvjfY/KTBAinS5O8sX2YAu1vYfAt13+3waUqOEmkPFyI3VTuwmweutUBgU9Nty1cNw1bC9Jy0NWy8TgnrU76vmLn0GcXTSfrCH5+K1f4hQOrLc=
