repositories:
  remote:
   - http://repo1.maven.org/maven2
   - https://stocksoftware.artifactoryonline.com/stocksoftware/public
   - https://stocksoftware.artifactoryonline.com/stocksoftware/oss
   - https://stocksoftware.artifactoryonline.com/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.13

  shade_task: org.realityforge.ant.shade:ant-shade-task:jar:0.1

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.0

  # GWT deps
  gwt_user: com.google.gwt:gwt-user:jar:2.8.2
  gwt_dev: com.google.gwt:gwt-dev:jar:2.8.2

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:1.0.2

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0-RC1

  elemental2_core: org.realityforge.com.google.elemental2:elemental2-core:jar:1.0.0-b14-2f97dbe
  elemental2_dom: org.realityforge.com.google.elemental2:elemental2-dom:jar:1.0.0-b14-2f97dbe
  elemental2_promise: org.realityforge.com.google.elemental2:elemental2-promise:jar:1.0.0-b14-2f97dbe

  braincheck: org.realityforge.braincheck:braincheck:jar:1.12.0

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.96

  arez_core: org.realityforge.arez:arez-core:jar:0.127
  arez_processor: org.realityforge.arez:arez-processor:jar:0.127

  autoservice: com.google.auto.service:auto-service:jar:1.0-rc3
  autocommon: com.google.auto:auto-common:jar:0.10
  javapoet: com.squareup:javapoet:jar:1.11.1
  guava: com.google.guava:guava:jar:25.0-jre

  compile_testing: com.google.testing.compile:compile-testing:jar:0.15
  truth: com.google.truth:truth:jar:0.39
